My_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backendBlog.urls')),

]
 

backendBlog/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

# from . import views

app_name = 'backendBlog'


urlpatterns = [
    path('categories/', categories_list, name='categories_list_url'),
    path('favorite/', add_favorite, name='add_favorite'),
    path('like/', like_article, name='like_article'),
    path('<str:slug>/comment/', add_comment, name='add_comment'),

    path('accounts/profile/delete', DeleteUserView.as_view(), name='profile_delete'),

    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', MainPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BlogLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('<str:slug>/', article_detail, name='article_detail'),
    path('accounts/login/', BlogLoginView.as_view(), name='login'),

    path('', article_list, name='home'),

    # path('', ArticleList.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backendBlog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


from django.dispatch import Signal



class MainUser(AbstractUser):
    can_delete_other_comments = models.BooleanField(default=False, db_index=True, verbose_name='Can delete all users coments?')
    about_me = models.CharField(max_length=255, blank=True, null=True)
    displayed_email = models.CharField(max_length=50, blank=True, null=True)

    class Meta(AbstractUser.Meta):
        pass


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

STATUS = (
    (0, 'Draft'),
    (1, 'Publish')
)

class Article(models.Model):
    title = models.CharField(max_length=255, unique = True, verbose_name='article title')
    slug = models.SlugField(max_length=255, unique=True, default='Some_string')
    overview = models.TextField(blank=False, verbose_name='article preview on frontpage')
    content = models.TextField(blank=False, verbose_name='article main text')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='date published')
    thumbnail = models.ImageField(blank=True, upload_to='thumbnails')
    status = models.IntegerField(choices=STATUS, default=0)
    categories = models.ManyToManyField(Category, blank=True, related_name='articles')
    likes = models.ManyToManyField(MainUser, related_name='likes', blank=True)
    favorite = models.ManyToManyField(MainUser, related_name='favorited', blank=True)


    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()




user_registrated = Signal(providing_args=['instance'])

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(MainUser, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

backendBlog/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import MainUser, user_registrated, Comment



class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Your e-mail')

    class Meta:
        model = MainUser
        fields = ('username', 'email', 'displayed_email', 'first_name', 'last_name', 'about_me')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password_first = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password_again = forms.CharField(label='Пароль (Повторно)', widget=forms.PasswordInput, help_text='Введите пароль повторно')

    def clean_password(self):
        password_first = self.cleaned_data['password_first']
        if password_first:
            password_validation.validate_password(password_first)
        return password_first

    def clean(self):
        super().clean()
        password_first = self.cleaned_data['password_first']
        password_again = self.cleaned_data['password_again']
        if password_first and password_again != password_again:
            errors = {'password_again': ValidationError('Пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password_first'])
        user.is_active = True
        if commit:
                user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = MainUser
        fields = ('username', 'email', 'password_first', 'password_again',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

backendBlog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.views import generic
from .models import Article, MainUser, Comment, Category
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib import messages

from .forms import ChangeUserInfoForm, RegisterUserForm, CommentForm
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView


#home page
def index(request):
    return render(request, 'basic.html')

#login page
class BlogLoginView(LoginView):
    template_name = 'backendBlog/login.html'


# class ArticleList(generic.ListView):
#
#     expression = '-pub_date'
#     queryset = Article.objects.filter(status=1).order_by(expression)
#     template_name = 'backendBlog/article_list.html'



#view for articles on frontpage and on sidebar (remake after class view)
def article_list(request):
    expression = '-pub_date'
    article_list = Article.objects.filter(status=1).order_by(expression)

    sidebar_list_recent = Article.objects.filter(status=1).order_by(expression)[:5]
    sidebar_list_popular = Article.objects.filter(status=1).order_by('-likes')[:5]

    context = {
        'article_list': article_list,
        'sidebar_list_popular': sidebar_list_popular,
        'sidebar_list_recent': sidebar_list_recent,
    }
    return render(request, 'backendBlog/article_list.html', context)


# class ArticleDetail(generic.DetailView):
#     model = Article
#     template_name = 'backendBlog/article_detail.html'

#view for article pages (remake after class view)

def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    is_liked = False
    if article.likes.filter(id=request.user.id).exists():
        is_liked = True
    is_favorite = False
    if article.favorite.filter(id=request.user.id).exists():
        is_favorite = True
    context = {
    'article': article,
    'is_liked': is_liked,
    'is_favorite': is_favorite,
    'total_likes': article.total_likes()
    }
    return render(request, 'backendBlog/article_detail.html', context)




@login_required
def profile(request):
    return render(request, 'backendBlog/profile_tmp/profile.html')

# class for profile logout
class BlogLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'backendBlog/profile_tmp/logout.html'



# class for changing user info
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = MainUser
    template_name = 'backendBlog/profile_tmp/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('backendBlog:profile')
    success_message = 'User info was changed'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


#class for changing passwor
class MainPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'backendBlog/profile_tmp/password_change.html'
    success_url = reverse_lazy('backendBlog:profile')
    success_message = 'Пароль успешно изменен'


#class for user registration
class RegisterUserView(CreateView):
    model = MainUser
    template_name = 'backendBlog/profile_tmp/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('backendBlog:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'backendBlog/profile_tmp/register_done.html'


#class for deleting user by himself
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = MainUser
    template_name = 'backendBlog/profile_tmp/delete_user.html'
    success_url = reverse_lazy('backendBlog:home')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# views for likes in article

def like_article(request):
    article = get_object_or_404(Article, id=request.POST.get('article_id'))
    is_liked = False
    if article.likes.filter(id=request.user.id).exists():
        article.likes.remove(request.user)
        is_liked = False
    else:
        article.likes.add(request.user)
        is_liked = True
    return redirect('backendBlog:article_detail', slug=article.slug)


# views for adding articles to favorite (same as likes tho)
def add_favorite(request):
    article = get_object_or_404(Article, id=request.POST.get('article_id'))
    is_favorite = False
    if article.favorite.filter(id=request.user.id).exists():
        article.favorite.remove(request.user)
        is_favorite = False
    else:
        article.favorite.add(request.user)
        is_favorite = True
    return redirect('backendBlog:article_detail', slug=article.slug)


#list of categories (no links set on templates)
def categories_list(request):
    categories = Category.objects.all()
    return render(request, 'backendBlog/categories_list.html', context={'categories' : categories})


# addig coments by users
def add_comment(request, slug):
    article = get_object_or_404(Article, slug=slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.name = request.user
            form.article = article
            form.save()

            return redirect('backendBlog:article_detail', slug=article.slug)
    else:
        form = CommentForm()
    template = 'backendBlog/add_comment.html'
    context = {'article': article, 'form':form, }
    return render(request, template, context)

templates_temp/templates/backendBlog/add_comment.html
{% extends 'basic.html' %}

{% block content %}

  <h1>Add new comment</h1>
  <form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

{% endblock content %}

templates_temp/templates/backendBlog/article_detail.html
{% extends 'basic.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class="card-text text-muted">{{ article.categories.all }} | {{ article.pub_date }}</p>
        <p class="card-text text-muted h6">{{ article.pub_date}} </p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>

  </div>
</div>
<form action="{% url 'backendBlog:like_article' %}" method="post">
  {% csrf_token %}
  {% if is_liked %}
  <button type="submit" name="article_id" value="{{ article.id }}" class="btn btn-primary">Dislike</button>
  {% else %}
  <button type="submit" name="article_id" value="{{ article.id }}" class="btn btn-primary">Like</button>
  {% endif %}
</form>

<form action="{% url 'backendBlog:add_favorite' %}" method="post">
  {% csrf_token %}
  {% if is_favorite %}
  <button type="submit" name="article_id" value="{{ article.id }}" class="btn btn-primary">Remove from favorite</button>
  {% else %}
  <button type="submit" name="article_id" value="{{ article.id }}" class="btn btn-primary">Add to favorite</button>
  {% endif %}
</form>

<hr />
<h1>Комментарии</h1>

  {% for comment in article.comments.all %}
    <p>{{ comment.created_on }}</p>
    <p>{{ comment.name }}</p>
    <p>{{ comment.body }}</p>
    {% empty %}
    <p>There is no comments</p>
  {% endfor %}
<a href="{% url 'backendBlog:add_comment' slug=article.slug %}">Добавить комментарий</a>

{% endblock content %}

templates_temp/templates/backendBlog/article_list.html
{% extends "basic.html" %}

{% block content %}

{% for Article in article_list %}



    <h2 class="name-block">{{ Article.title }}</h2>

    <p class="block-content">
      {{ Article.overview | truncatewords:30 }}
    </p>

    <form action="{% url 'backendBlog:article_detail' Article.slug  %}">
      <button type="submit" class="button-read-more">Читать далее</button>
    </form>

{% endfor %}
<main>
  <div class="side-bar">
    {% include "backendBlog/sidebar.html" %}
  </div>
</main>


{% endblock %}

templates_temp/templates/backendBlog/login.html
{% extends "basic.html" %}


{% block title %}Логин{% endblock title %}

{% block content %}

<h2>Вход</h2>
{% if user.is_authenticated %}
<p>
  Hello, {{ user.username }}
</p>.
{% else %}
<p>Выполните вход</p>


<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Войти</button>
</form>

{% endif %}

{% endblock content %}

templates_temp/templates/backendBlog/sidebar.html
<!-- Sidebar Widgets Column -->

  <div class="select">
    <a>Последние посты</a>
    <a>Популярные посты</a>
    <a>Набирающие популярность</a>
  </div>
  <div class="side-bar-content">
    <ul class="side-bar-links side-bar-links-1">
      <li><a href="#">11111111</a> </li>
      <li><a href="#">11111111</a> </li>
      <li><a href="#">11111111</a> </li>
      <li><a href="#">11111111</a> </li>
      <li><a href="#">11111111</a> </li>
    </ul>
    <ul class="side-bar-links side-bar-links-2">
      <li><a href="#">222222</a> </li>
      <li><a href="#">222222</a> </li>
      <li><a href="#">222222</a> </li>
      <li><a href="#">222222</a> </li>
      <li><a href="#">222222</a> </li>
    </ul>
    <ul class="side-bar-links side-bar-links-3">
      <li><a href="#">333333333</a> </li>
      <li><a href="#">333333333</a> </li>
      <li><a href="#">333333333</a> </li>
      <li><a href="#">333333333</a> </li>
      <li><a href="#">333333333</a> </li>
    </ul>
  </div>