My_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backendBlog.urls')),

]
 

backendBlog/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

# from . import views

app_name = 'backendBlog'


urlpatterns = [
    path('categories/', categories_list, name='categories_list_url'),
    path('favorite/', add_favorite, name='add_favorite'),
    path('like/', like_article, name='like_article'),
    path('<str:slug>/comment/', add_comment, name='add_comment'),

    path('accounts/profile/delete', DeleteUserView.as_view(), name='profile_delete'),

    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', MainPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BlogLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('<str:slug>/', article_detail, name='article_detail'),
    path('accounts/login/', BlogLoginView.as_view(), name='login'),

    path('', article_list, name='home'),

    # path('', ArticleList.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/basic.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

{% include "head.html" %}
<body>

{% include "header.html" %}


{% block content %}

{% endblock content %}




{% include "footer.html" %}

</body>

</html>

templates/footer.html
<footer id="part-footer">
  <a href="#" name="#bottom"></a>
  <div class="information">
    <p>ОАО*****</p>
    <p>Адрес:</p>
    <p>Тел.</p>
    <p>Тел.</p>
  </div>
</footer>

templates/head.html
{% load static %}

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}Document{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</head>

templates/header.html
{% load static %}

<header>
  <div class="header-block">
    <div class="header-block-1">
      <nav>
        <a href="{% url 'backendBlog:home' %}" class="nav-link">Главная</a>
        <a href="#part-footer" class="nav-link" name="bottom">О нас</a>

      <form class="form-for-area-for-search">
        <input type="search" class="area-for-search">
        <button type="submit" class="button-search">Поиск</button>
      </form>
    </nav>
    </div>
    <div class="header-block-2">
      {% if user.is_authenticated %}
      <form action="{% url 'backendBlog:logout' %}" class="form-for-button-reg">
        <button type="submit" class="button-reg"> ВЫХОД</button>
      </form>
      <form action="{% url 'backendBlog:profile' %}" class="form-for-button-reg">
      <button type="submit" class="button-reg-1">МОЙ АККАУНТ</button>
      </form>
      {% else %}
      <form action="{% url 'backendBlog:login' %}" class="form-for-button-reg">
        <button type="submit" class="button-reg"> ВХОД</button>
      </form>
      <form action="{% url 'backendBlog:register' %}" class="form-for-button-reg">
      <button type="submit" class="button-reg-1">РЕГИСТРАЦИЯ</button>
      </form>
      {% endif %}
    </div>
  </div>
  <h1 class="type-it">#Back-end</h1>
</header>

templates/sidebar.html
{% load static %}

  <div class="select-link">
    <a>Последние посты</a>
    <a>Популярные посты</a>
    <a>Набирающие популярность</a>
  </div>
  <div class="side-bar-content">
    <ul class="side-bar-links ">

      {% for Article in sidebar_list_recent %}
      <li><a href="{% url 'backendBlog:article_detail' Article.slug  %}">{{ Article.title }}</a></li>
      {% endfor %}

    </ul>
    <ul class="side-bar-links side-bar-links-hide ">

      {% for Article in sidebar_list_popular %}
      <li><a href="{% url 'backendBlog:article_detail' Article.slug  %}">{{ Article.title }}</a></li>
      {% endfor %}

    </ul>
    <ul class="side-bar-links side-bar-links-hide">
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
      <li><a href="#">333333333</a></li>
    </ul>
  </div>